---
title: "Coastal watersheds delineation"
author: "Kelly Hondula"
date: "3/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(dplyr)
library(leaflet)
library(readr)
library(tidyr)
```


```{r}
# download.file("https://water.usgs.gov/GIS/dsdl/huc250k_shp.zip", destfile = "data/wbd.zip")
# unzip("data/wbd.zip", exdir = "/nfs/khondula-data/wbd/")
huc250k <- sf::read_sf("/nfs/khondula-data/wbd/huc250k_shp/huc250k.shp") %>% st_transform(4326)
head(huc250k)
```

# coastal sampling point coordinates

```{r}
# download.file("https://raw.githubusercontent.com/ecodasXIII/StoichPatterns/master/data/assessed_ncca2010_siteinfo.revised.06212016.csv", destfile = "data/ncaa_coords.csv")
```

```{r}
ncaa_coords <- readr::read_csv("data/ncaa_coords.csv")
table(ncaa_coords$MAP_DATUM)
```

95 sites without a reported map datum, and another 11 with NA - need to decide which datum to use for those. For now make them all into wgs84 since that is what the majority of them are

```{r}
ncaa_coords_wgs84 <- ncaa_coords %>% 
  mutate(MAP_DATUM = replace_na("WGS84")) %>% 
  filter(MAP_DATUM %in% c("WGS84", "NOT REPORTED")) %>%
  st_as_sf(coords = c("ALON_DD", "ALAT_DD"), crs = 4326)

ncaa_coords_nad83 <- ncaa_coords %>% 
  filter(MAP_DATUM == "NAD83") %>%
  st_as_sf(coords = c("ALON_DD", "ALAT_DD"), crs = 4269)

ncaa_coords_sf <- ncaa_coords_nad83 %>% 
  st_transform(crs = 4326) %>%
  rbind(ncaa_coords_wgs84)
rm(ncaa_coords, ncaa_coords_nad83, ncaa_coords_wgs84)
ncaa_coords_sf %>% st_write("/nfs/khondula-data/coastalsheds/ncaa_coords_wgs84.shp")
```


Plot first one 

```{r}
ncaa_coords_sf[1,] %>%
  leaflet() %>%
  addTiles() %>%
  addMarkers()
```

```{r}
wbd <- "https://hydro.nationalmap.gov/arcgis/services/wbd/MapServer/WMSServer"
nlcd <- "https://smallscale.nationalmap.gov/arcgis/services/LandCover/MapServer/WMSServer"

ncaa_coords_sf %>%
  st_transform(5070) %>%
  st_buffer(5000) %>%
  st_transform(4326) %>%
  # slice(2) %>%
  leaflet() %>% 
  addTiles() %>%
  # addProviderTiles(providers$Esri.WorldImagery) %>%
  addPolygons(group = "5km buffer") %>%
  addMarkers(data = ncaa_coords_sf, group = "points",
             clusterOptions = markerClusterOptions()) %>%
  addWMSTiles(nlcd, layers = "1",
              options = WMSTileOptions(format = "image/png", transparent = TRUE),
              group = "NLCD") %>%
    addWMSTiles(wbd, layers = "7",
              options = WMSTileOptions(format = "image/png", transparent = TRUE),
              group = "WBD transparent") %>%
  addLayersControl(overlayGroups = c("NLCD", "WBD transparent", "points", "5km buffer"))
  
```

```{r}
nhdp <- "https://basemap.nationalmap.gov/arcgis/services/USGSHydroCached/MapServer/WMSServer"
wbd <- "https://hydro.nationalmap.gov/arcgis/services/wbd/MapServer/WMSServer"

ncaa_coords_sf %>%
  st_transform(5070) %>%
  st_buffer(5000) %>%
  st_transform(4326) %>%
  # slice(2) %>%
  leaflet() %>% 
  addTiles(group = "OSM") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Esri imagery") %>%
  addPolygons(group = "5km buffer") %>%
  addMarkers(data = ncaa_coords_sf, group = "points", label = ~SITE_ID,
             clusterOptions = markerClusterOptions()) %>%
  addWMSTiles(nhdp, layers = "0",
              options = WMSTileOptions(format = "image/png", transparent = TRUE),
              group = "NHD") %>%
      addWMSTiles(wbd, layers = "7",
              options = WMSTileOptions(format = "image/png", transparent = TRUE),
              group = "WBD transparent") %>%
    addLayersControl(baseGroups = c("OSM", "Esri imagery"), overlayGroups = c("NLCD","NHD", "WBD transparent", "points", "5km buffer"))

  
```

