---
title: "Watershed delineation"
author: "Kelly Hondula"
date: "3/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("nhdR")
# library(nhdR)
# library(FedData)
# if (!require(devtools)) install.packages('devtools')
# devtools::install_github("giswqs/whiteboxR")
# library(whitebox)
# library(raster)
library(igraph)
library(sf)
library(fs)
library(dplyr)
```

```{r}
# zipfiles <- sprintf("https://prd-tnm.s3.amazonaws.com/StagedProducts/Hydrography/WBD/HU2/Shape/WBD_%s_HU2_Shape.zip", stringr::str_pad(1:22, width = 2, pad = "0"))
# destfiles <- sprintf("/nfs/khondula-data/wbd/huc_%s.zip", stringr::str_pad(1:22, width = 2, pad = "0"))
# purrr::walk2(.x = zipfiles, .y = destfiles, .f = ~download.file(url = .x, destfile = .y))
# unzipfiles <- sprintf("/nfs/khondula-data/wbd/Shape_%s", stringr::str_pad(1:22, width = 2, pad = "0"))
# purrr::walk2(.x = destfiles, .y = unzipfiles, .f = ~unzip(.x, exdir = .y))
```


```{r}
# download.file(url = "https://prd-tnm.s3.amazonaws.com/StagedProducts/Hydrography/WBD/National/GDB/WBD_National_GDB.zip", destfile = "/nfs/khondula-data/wbd/nationalwbd.zip")
# unzip( "/nfs/khondula-data/wbd/nationalwbd.zip", exdir = "/nfs/khondula-data/wbd/")
# huc 2 gdb file downloaded from 
# https://nrcs.app.box.com/v/gateway/folder/39640323180
```

```{r}
data_dir_wbd <- "/nfs/khondula-data/wbd"
data_dir_coastalsheds <- "/nfs/khondula-data/coastalsheds"
```

```{r}
ncaa_coords_sf_prj <- st_transform(ncaa_coords_sf, 4269)
unique(ncaa_coords_sf_prj$SITE_) %>% length()
# ncaa_siteID <- ncaa_coords_sf_prj$SITE_ID[4]
ncaa_siteID <- "NCCA10-1140"
my_ncaa_pt <- filter(ncaa_coords_sf_prj, SITE_ == ncaa_siteID)[1]
mypt_id <- ncaa_siteID
```

find which huc 2 the point is in

```{r}
huc2 <- st_read(file.path(data_dir_wbd, "wbdhu2_a_us_september2018.gdb")) %>% st_transform(4269)
my_huc2_mat <- st_contains(huc2, my_ncaa_pt, sparse = FALSE)
my_huc2_id <- which(apply(my_huc2_mat, 1, any))
my_huc2 <- huc2[my_huc2_id,]
my_huc2_id <- my_huc2$HUC2 %>% as.character()
my_huc2_id
```

then read in HUC 12s

```{r}
huc12_filepath <- file.path(data_dir_wbd, sprintf("Shape_%s/Shape/WBDHU12.shp", my_huc2_id))
huc12 <- st_read(huc12_filepath) %>% st_transform(4269)

my_huc12_mat <- st_contains(huc12, my_ncaa_pt, sparse = FALSE)
my_huc12_id <- which(apply(my_huc12_mat, 1, any))
my_huc12 <- huc12[my_huc12_id,]
my_huc12_id <- my_huc12$HUC12 %>% as.character()
my_huc12_id
```

function to find all upstream HUC12s
```{r}

huc12_edgelist <- huc12 %>% st_drop_geometry() %>% dplyr::select(HUC12, ToHUC)
huc12_network <- huc12_edgelist %>% igraph::graph_from_data_frame()
paths_in <- igraph::all_simple_paths(huc12_network, from = my_huc12_id, mode = "in")
upstream_huc12s <- sapply(paths_in, names) %>% unlist() %>% unique()
upstream_huc12s
```

Filter those from huc 12 dataset and save with site ID

```{r}
upstream_huc12s_sf <- dplyr::filter(huc12, HUC12 %in% upstream_huc12s) %>% rbind(my_huc12)
upstream_huc12s_sf_union <- upstream_huc12s_sf %>% st_union()
```

Map
```{r}
leaflet() %>%
  addTiles() %>%
  addPolygons(data = upstream_huc12s_sf_union) %>%
  addMarkers(data = my_ncaa_pt)
```

save
```{r}
st_write(upstream_huc12s_sf, file.path(data_dir_coastalsheds, "ncaa_huc12sheds", 
                                         sprintf("%s_huc12shed.shp", mypt_id)))
st_write(upstream_huc12s_sf_union, file.path(data_dir_coastalsheds, "ncaa_huc12sheds_union",
                                               sprintf("%s_huc12shed_union.shp", mypt_id)))
```

Everything above as a function of a point site id (for iteration)

```{r}
save_huc12shed_for_pt <- function(ncaa_siteID){
  # locations for data
  data_dir_wbd <- "/nfs/khondula-data/wbd"
  data_dir_coastalsheds <- "/nfs/khondula-data/coastalsheds"
  out_path <- file.path(data_dir_coastalsheds, "ncaa_huc12sheds")
  out_path2 <- file.path(data_dir_coastalsheds, "ncaa_huc12sheds_union")
  if(!fs::dir_exists(out_path)){fs::dir_create(out_path)}
  if(!fs::dir_exists(out_path2)){fs::dir_create(out_path2)}
  # read in ncaa coordinates
  ncaa_coords_sf_prj <- st_read(file.path(data_dir_coastalsheds, "ncaa_coords", "ncaa_coords_wgs84.shp")) %>%
    st_transform(4269) # project coords to WBD prj
  # select one point
  my_ncaa_pt <- dplyr::filter(ncaa_coords_sf_prj, SITE_ == ncaa_siteID)[1]
  # mypt_id <- my_ncaa_pt$SITE_
  mypt_id <- ncaa_siteID
  
  # identify which huc 2 the point is in
  huc2 <- st_read(file.path(data_dir_wbd, "wbdhu2_a_us_september2018.gdb")) %>% st_transform(4269)
  my_huc2_mat <- st_contains(huc2, my_ncaa_pt, sparse = FALSE)
  my_huc2_id <- which(apply(my_huc2_mat, 1, any))
  my_huc2 <- huc2[my_huc2_id,]
  my_huc2_id <- my_huc2$HUC2 %>% as.character()
  
  # read in the corresponding huc 12s
  huc12_filepath <- file.path(data_dir_wbd, sprintf("Shape_%s/Shape/WBDHU12.shp", my_huc2_id))
  huc12 <- st_read(huc12_filepath) %>% st_transform(4269)
  
  # find which huc 12 point is in
  my_huc12_mat <- st_contains(huc12, my_ncaa_pt, sparse = FALSE)
  my_huc12_id <- which(apply(my_huc12_mat, 1, any))
  my_huc12 <- huc12[my_huc12_id,]
  my_huc12_id <- my_huc12$HUC12 %>% as.character()
  
  # convert to graph to find all upstream huc 12s
  huc12_edgelist <- huc12 %>% st_drop_geometry() %>% dplyr::select(HUC12, ToHUC)
  huc12_network <- huc12_edgelist %>% igraph::graph_from_data_frame()
  paths_in <- igraph::all_simple_paths(huc12_network, from = my_huc12_id, mode = "in")
  upstream_huc12s <- sapply(paths_in, names) %>% unlist() %>% unique()
  
  # filter from huc 12 object and save
  upstream_huc12s_sf <- dplyr::filter(huc12, HUC12 %in% upstream_huc12s) %>% 
    rbind(my_huc12) # combine with original huc12 in case no upstream ones found
  upstream_huc12s_sf_union <- upstream_huc12s_sf %>% st_union()
  st_write(upstream_huc12s_sf, file.path(data_dir_coastalsheds, "ncaa_huc12sheds", 
                                         sprintf("%s_huc12shed.shp", mypt_id)))
  st_write(upstream_huc12s_sf_union, file.path(data_dir_coastalsheds, "ncaa_huc12sheds_union",
                                               sprintf("%s_huc12shed_union.shp", mypt_id)))

}
```

Iterate over all points
```{r}
data_dir_coastalsheds <- "/nfs/khondula-data/coastalsheds"
ncaa_coords_sf_prj <- st_read(file.path(data_dir_coastalsheds, "ncaa_coords", "ncaa_coords_wgs84.shp")) %>%
    st_transform(4269) 
ncaa_siteIDs <- ncaa_coords_sf_prj$SITE_ %>% unique()
save_huc12shed_for_pt(ncaa_siteID = ncaa_siteIDs[4])
# system.time(save_huc12shed_for_pt(ncaa_siteID = ncaa_siteIDs[3]))
purrr::walk(ncaa_siteIDs, ~save_huc12shed_for_pt(.x))
```

```{r}
# find which points havent beendone yet
huc12shed_shpfiles <- fs::dir_ls(file.path(data_dir_coastalsheds, "ncaa_huc12sheds_union"), glob = "*.shp")
huc12shed_ids <- basename(huc12shed_shpfiles) %>% stringr::str_replace("_huc12shed_union.shp", "")
ncaa_siteIDs_toget <- ncaa_siteIDs[!ncaa_siteIDs %in% huc12shed_ids]
```

```{r}
library(rslurm)
pars <- data.frame(ncaa_siteID = ncaa_siteIDs_toget, stringsAsFactors = FALSE)

sjob <- rslurm::slurm_apply(save_huc12shed_for_pt, pars, 
                            jobname = "coastal",
                            slurm_options = list(partition = "sesync", 
                                                 time = "12:00:00"),
                            nodes = 8, cpus_per_node = 2, 
                            submit = TRUE)

print_job_status(sjob)
# rslurm::cancel_slurm(sjob)
```

